name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Unit tests
      run: ./gradlew test --stacktrace

  instrumented-test:
    name: Run Instrumented Tests
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 30]
      fail-fast: false
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Emulator tests API ${{ matrix.api-level }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew connectedCheck

  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Build APK
      run: ./gradlew assemble --stacktrace
    - name: Upload debug APK
      uses: actions/upload-artifact@v2
      with:
        name: CurrentView-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
    - name: Upload release APK
      uses: actions/upload-artifact@v2
      with:
        name: CurrentView-release-apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: error
